### ISSUE TITLE
0 speed when snow/stadium gate intersects checkpoint

### ISSUE THREAD

**Issue by ezio416** [RuurdBijlsma/tm-split-speeds#10]
Since the car changes at the same moment it goes through the checkpoint, maybe the plugin isn't able to grab a speed for either car state? Example from Winter 2024-25 (happens on a couple different checkpoints, but not always):
<img width="431" alt="Screenshot 2024-01-09 180038" src="https://github.com/RuurdBijlsma/tm-split-speeds/assets/37951898/d1289c20-907e-41b6-8551-88740e352e91">

**Comment by RuurdBijlsma** [comment]
Pretty sure this has been fixed a while, but I just updated the plugin and should definitely be fixed now

**Comment by ezio416** [comment]
hey sorry but this is not fixed

https://github.com/RuurdBijlsma/tm-split-speeds/assets/37951898/f98d9708-ced6-499b-a90d-3d2e230062dd

**Comment by RuurdBijlsma** [comment]
Hmm weird, I can maybe look at it sunday

**Comment by ezio416** [comment]
It seems to happen less often with rally car so I'm having trouble getting it again, but I can still reproduce it on Winter 2024-25 cp2

**Comment by ezio416** [comment]
I also just had it happen on the map Snolly 3 times in a row:


https://github.com/RuurdBijlsma/tm-split-speeds/assets/37951898/ffe109c9-1cbf-4a8e-94d1-074dac1589f2

**Comment by RuurdBijlsma** [comment]
i found out what's causing it, i made an issue for this in the vehiclestate repo. https://github.com/openplanet-nl/vehiclestate/issues/17

If this gets resolved the issue should be gone

**Comment by RuurdBijlsma** [comment]
i fixed it with a workaround, when the next update gets released this issue should be gone

**Comment by ezio416** [comment]
The workaround seems good, I'm not able to reproduce anymore. Thank you!
