### ISSUE TITLE
Incorrect splits for Rally car 

### ISSUE THREAD

**Issue by Brainy0207** [RuurdBijlsma/tm-split-speeds#13]
I noticed something weird.

When driving the Rally car sometimes the splits seem to be completely wrong.
Like I get green splits for multiple CPs, but still lose time (and vice versa).

I will try to take a video later.

**Comment by Brainy0207** [comment]
I think this is actually related to #10 
Because I realized I only see it when the transformation gate is intersecting a checkpoint.

**Comment by Brainy0207** [comment]
I might be imagining things at this point, but i could have sworn I saw split discrepancies that were different from the 0 speed glitch. I tried to replicate it but I couldn't.

Here is the video from a test I did, but it only shows that sometimes the speed is reported as 0.

https://streamable.com/9csx5q

**Comment by RuurdBijlsma** [comment]
Any chance this was fixed with the latest openplanet update? I can't get the same issue to reproduce with a similar map as the on in your streamable

**Comment by RuurdBijlsma** [comment]
I say this also because i've had an issue like this with snow car before, but that was fixed by an update to VehicleState, which is an openplanet feature that split speeds depends on

**Comment by Brainy0207** [comment]
Doesn't seem to be fixed, it's still happening on my test map.
Unless there is an openplanet beta I don't have.

**Comment by Brainy0207** [comment]
I have attached my test map:
[RallyTest.Map.Gbx.zip](https://github.com/RuurdBijlsma/tm-split-speeds/files/14473788/RallyTest.Map.Gbx.zip)

**Comment by RuurdBijlsma** [comment]
interestingly i can only reproduce this when allowing trackmania only 2 cores from my CPU

**Comment by RuurdBijlsma** [comment]
i'm curious, what fps do you get? and what cpu do you have?

**Comment by Brainy0207** [comment]
I am running on a Ryzen 7 5800. Playing at 60 FPS (because of VSync and 60 Hz monitors).

**Comment by RuurdBijlsma** [comment]
lol same cpu as me, except i have 5800x3d, weird though that i can't reproduce it without limiting cpu. Maybe it's a framerate thing. i'll try messing with that

**Comment by RuurdBijlsma** [comment]
yea it's fps

**Comment by RuurdBijlsma** [comment]
i made an issue for this in the vehiclestate repo since that's whats causing it. https://github.com/openplanet-nl/vehiclestate/issues/17

If this gets resolved the issue should be gone

**Comment by RuurdBijlsma** [comment]
i fixed it with a workaround, when the next update gets released this issue should be gone
